In [9]:
import numpy as np
import matplotlib.pyplot as plt

from keras import models
from keras.layers import Dense, Conv1D, Reshape, Flatten, Lambda
from keras import backend as K

import tensorflow as tf


# 이 노트북에서는 새로 나온 함수와 클래스들에 대해서 실습을 해보면서 그 내용을 확인합니다.

## mean

In [18]:
x = np.arange(24).reshape(2,3,4).astype('float32')
x.shape

(2, 3, 4)

In [19]:
x

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]],

       [[ 12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.],
        [ 20.,  21.,  22.,  23.]]], dtype=float32)

In [20]:
x = tf.convert_to_tensor(x)

In [25]:
with tf.Session() as sess:
    keepdims = [True, False]
    
    for keep in keepdims:    
        rs = sess.run(K.mean(x, axis=-1, keepdims=keep))
        print(rs.shape)
        print(rs)

(2, 3, 1)
[[[  1.5]
  [  5.5]
  [  9.5]]

 [[ 13.5]
  [ 17.5]
  [ 21.5]]]
(2, 3)
[[  1.5   5.5   9.5]
 [ 13.5  17.5  21.5]]


## Conv1D

https://keras.io/layers/convolutional/

In [30]:
def conv1d():
    ni_D = 10
    m = models.Sequential()
    m.add(Reshape((ni_D, 1), input_shape=(ni_D,)))
    m.add(Conv1D(5, 1, activation=None))
    m.add(Conv1D(1, 1))
    m.compile(optimizer='adam', loss='binary_crossentropy')
    return m

In [31]:
m = conv1d()

In [44]:
x = np.random.randint(low=0, high=10, size=(2,10))
m.predict(x)

array([[[ 3.21412921],
        [ 0.        ],
        [ 1.78562713],
        [ 0.        ],
        [ 1.42850184],
        [ 1.78562713],
        [ 0.71425092],
        [ 0.35712546],
        [ 2.14275265],
        [ 3.21412921]],

       [[ 2.14275265],
        [ 2.85700369],
        [ 1.07137632],
        [ 0.71425092],
        [ 0.        ],
        [ 2.14275265],
        [ 1.07137632],
        [ 2.14275265],
        [ 1.78562713],
        [ 1.78562713]]], dtype=float32)

## concatenate

In [43]:
Real = np.arange(6).reshape(2,3)
Gen  = np.arange(12).reshape(4,3)

np.concatenate([Real, Gen], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])